### PR TITLE
feature to list all tasks / updated gitignore

### PR DESCRIPTION
**Pull request by henriquechehad**

### CODE REVIEW

**Comment by henriquechehad** [comment]
I needed a feature to list all registered tasks and implemented it in this PR, check if you need this feature.

**Comment by coleifer** [comment]
While I appreciate the effort that went into this, I'm going to pass on merging. Huey already logs the list of registered commands, by the way. The code is in consumer.py:

https://github.com/coleifer/huey/blob/3a13cdb37cd146112f196e0c9c9436bed3c437ec/huey/consumer.py#L422-L426

The output looks like:

```
[2016-06-15 22:22:53,099] INFO:huey.consumer:MainThread:The following commands are available:
+ try_thrice
+ slow
+ every_five_mins
+ count_beans
```

**Comment by henriquechehad** [comment]
@coleifer thanks, I was logging with Django logger, not used the --log-file option. I will use this option. 

It would not be interesting to use to show in console?

**Comment by coleifer** [comment]
It should be possible to attach a console log handler, so this is do-able.

**Comment by henriquechehad** [comment]
Where is the console log handler implementation? I didn't located

**Comment by coleifer** [comment]
`from logging import StreamHandler`

**Comment by henriquechehad** [comment]
I configured the logfile in django, but it didn't logged the registered tasks in logfile. What can it be?

     root@cb891d57c8b5:~# cat /tmp/huey.log
     [2016-06-20 15:29:25,594] DEBUG:urllib3.util.retry:Scheduler:Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0)
     [2016-06-20 15:29:25,595] INFO:urllib3.connectionpool:Scheduler:Starting new HTTP connection (1): elasticsearch
     [2016-06-20 15:29:25,601] DEBUG:urllib3.connectionpool:Scheduler HTTP/1.1" 200 994



Django conf:
     
     HUEY = {
         'name': 'NAME',
         'connection': {'host': 'redis', 'port': 6379},
         'consumer': {
             'workers': 16, 'worker_type': 'worker',
             'loglevel': 'DEBUG', 'logfile': '/tmp/huey.log',
         },
     }

**Pull request closed without merging**
