### PR TITLE
Fix for #187

### PR DESCRIPTION
**Pull request by camilonova**

### CODE REVIEW

**Comment by camilonova** [comment]
@coleifer This is working fine on production, would you merge this and cut a release?

**Comment by coleifer** [comment]
Theoretically anything passed in on the command-line should override the settings in `settings.HUEY`, which is why it is in the order you see.

**Comment by camilonova** [comment]
But the settings in `settings.HUEY` are overriden by the default command line options. This was the only way I could make it work.

**Comment by camilonova** [comment]
@coleifer Any updates?

**Comment by Antwan86** [comment]
@coleifer @camilonova This implementation works but it would be better to have a proper options refactoring. See my [comment](https://github.com/coleifer/huey/issues/187#issuecomment-291136441).

**Pull request closed without merging**
