### PR TITLE
Allow rolling deploy with a switch from RedisHuey to PriorityRedisHuey 

### PR DESCRIPTION
**Pull request by tardate**
RedisHuey and PriorityRedisHuey use a different redis data type for the redis queue. This can lead to a catch-22 gotcha when deploying a change to PriorityRedisHuey on a busy application:

* if there is a queue backlog at the time of the switch, the queue data type will be wrong
* all PriorityRedisHuey attempts to enqueue/dequeue will fail with redis error `ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value`. In fact, huey fails to startup.
* ... and game over. cannot proceed without manual intervention to clear the queue

This change adds a backwards-compatibility fallback, allowing PriorityRedisHuey to continue to handle tasks that are a hold-over from RedisHuey. When the queue backlog is finally cleared, it will then switch to PriorityRedisHuey data type and honoring priorities. While waiting for the change, the queue will continue to behave like RedisHuey and ignore priority assignments.

### CODE REVIEW

**Comment by coleifer** [comment]
I'm going to pass on this change, thanks though.

**Comment by coleifer** [comment]
What I would suggest, instead, is to just point your `PriorityRedisHuey` at a different database number (e.g. `RedisHuey(db=0)` -> `PriorityRedisHuey(db=15)` -- then let your old consumer empty the queue while your new one is up and running to accept new tasks.

**Comment by tardate** [comment]
that's fine @coleifer - we have got our use out of the change for our deployment challenge and can now revert to mainline.

would you accept instead a little doc update to point out the issue and workarounds? It's a problem that can easily slip through dev/testing to unexpectedly ruin someone's day with an unexpected production outage without an obvious fix other than to rollback + bad language;-)

**Comment by coleifer** [comment]
Yes, I think a doc addition would probably make sense.

**Pull request closed without merging**
