### PR TITLE
Improve extensibility

### PR DESCRIPTION
**Pull request by egor-georgiev**

### CODE REVIEW

**Comment by egor-georgiev** [comment]
Hello, thanks for your work on Huey. I have added several ways to facilitate extensibility of Huey components, here are the use cases I added them for:

1. Moving consumer event loop logic to a separate method allows to insert custom operations into every iteration of event loop without checking that updates do not break custom logic (by calling 'super()). For instance, in our codebase, we make sure that every iteration of consumer event loop touches a file as a means of health-checking Consumer process in container runtime.
2. Adding `consumer_class`, `task_wrapper_class` allows to use custom classes for Huey `Consumer` and `TaskWrapper` without overriding whole `task`, `create_consumer` methods. To illustrate the use case, in our codebase we add several new convenience methods to Consumer class in order to facilitate health-check logic described in 1. We also plan on overriding `TaskWrapper`'s `s` and `schedule` methods in order to register task id <-> task name mapping in redis storage.

**Comment by egor-georgiev** [comment]
I brought `task_wrapper_class` as a `@property` in order not to toss around class declarations (property is lazy, but attribute is not, therefore, adding it as an attribute and not re-ordering declarations would cause a `NameError`).

**Comment by egor-georgiev** [comment]
@coleifer thank you for your quick response! Do you have in mind a timeline for the next release?

**Comment by coleifer** [comment]
Not particularly, no, feel free to run on master in the meantime - I generally keep it stable & tests passing.

**Pull request closed without merging**
